SELECT * FROM BIONEMO_DB.PUBLIC.PROTEIN_SEQUENCE_FUNCTION;

SELECT
    UNIPROTID,
    VECTOR_L2_DISTANCE(EMB, (
        SELECT EMB FROM BIONEMO_DB.PUBLIC.PROTEIN_SEQUENCE_FUNCTION WHERE SEQUENCE = 'LICHRVHGLQTCEPDQKFCFRKTTMFFPNHPVLLMGCTSSCPTEKYSVCCSTDKCNK'
    )::VECTOR(FLOAT, 1024)) AS DISTANCE,
    EMB
FROM BIONEMO_DB.PUBLIC.PROTEIN_SEQUENCE_FUNCTION
ORDER BY DISTANCE ASC
LIMIT 4;
